language: node_js
node_js:
- '4.1'

install:
- npm install --loglevel=error --no-progress

script:
- gulp build --prod

deploy:
  provider: gcs
  access_key_id: GOOGOXPMUFLBCAJOTTQW
  secret_access_key:
    secure: Y6aTEgQMVyXz7Xnp+liVb/jxuRW3mLe7SdcmXUQ1RO4a4EDoqzcpDOeleOqdxxTXUwfcZ04ClSgz1FCO6rhDVEXeKMNd1/zMg2bVXYb0vLaGhZLir6HW4LQWpcJMdkCCnIr72vMoTSGzhnymCRC3w3jlKWKeZPzBD3DHaHc/KFN+RflrB836UzYzo3D2RrU3i1r+2swYw2FWlPFHIRwjC945UYKcHayfGU0YVZEa82mEN0KPv6kDlP/d4K3Ghl+jPhuHOrExUebAv5QMrWgwXck0LpgT/Snmvcc109SaChEy1KHi0gEZpUY2iCtDTCRvhM2Cik5sj8ky3gAIiM+LmfaPIirplgvSWqh/npNYpYzvR34nmkM6Gp82qeQAAHXZ3J7qzG5U0RCTRFvr69t3K3gsOl3k6Ptw3IJ3rz3vPH/5Jzrjjx85JNtpKcZA4u97wKa5u3VcXIl+vjwNGNTctB6vD27VF0J0X73U8avTPHH2aMb5YNuogOgWCsd5UGYlrK0mZOGVjXhvE/bIgIS+IRMMcNtyNxjycxd8eI74Pp/Zn3FnOeYPYeTZKkH5fmgOJNhkaDD0vNQwKgcIA6Dh/+QktVd9Q0I6k3hn9SDeETkHDNJm7ok1KDFPz2ewbHUOh8PoQ4gJpmE2ko8tRvqKE6KLvnFLZfos6vvsDU2LA7A=
  bucket: jsconf.bdvs.info
  skip_cleanup: true
  local-dir: dist
  acl: public-read
  cache_control: "no-cache"
  on:
    repo: jsis/jsconf.is
