language: node_js
node_js:
- '4.1'

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_modules

# script needed to test, because defaults don't work on osx
script:
  - npm run lint
  - npm run build
