siteTitle="JSConf Iceland: August 25th — 26th 2016"
siteDescription="A two day JavaScript conference in Reykjavik, Iceland."

[[sponsors]]
name = "Advania"
website = "https://advania.is"
level = "platinum"
image = "advania.png"
imagePadding = true

[[sponsors]]
name = "AMP Project"
website = "https://www.ampproject.org"
level = "platinum"
image = "google.png"
imagePadding = true

[[sponsors]]
name = "Aranja"
website = "https://aranja.com"
level = "silver"
image = "aranja.svg"
imagePadding = false

[[sponsors]]
name = "Bloomberg"
website = "https://bloomberg.com"
level = "silver"
image = "bloomberg.svg"
imagePadding = true

[[sponsors]]
name = "CCP"
website = "https://ccpgames.com"
level = "bronze"
image = "ccp.png"
imagePadding = true

[[sponsors]]
name = "Highcharts"
website = "https://highcharts.com"
level = "silver"
image = "highcharts.png"
imagePadding = true

[[sponsors]]
name = "Landsbankinn"
website = "https://www.landsbankinn.is"
level = "silver"
image = "landsbankinn.jpg"
imagePadding = false

[[sponsors]]
name = "Mozilla"
website = "https://www.mozilla.org"
level = "silver"
image = "mozilla.svg"
imagePadding = true

[[sponsors]]
name = "Tempo"
website = "http://tempo.io"
level = "silver"
image = "tempo.svg"
imagePadding = true

[[sponsors]]
name = "UENO."
website = "https://ueno.co/"
level = "bronze"
image = "ueno.png"
imagePadding = false

[[sponsors]]
name = "UPPERQUAD"
website = "http://upperquad.com/"
level = "silver"
image = "upperquad.png"
imagePadding = true

[[sponsors]]
name = "VIEW SOURCE"
website = "https://viewsourceconf.org/"
level = "bronze"
image = "viewsourceconf.jpg"
imagePadding = false
